In [1]:
import tensorflow as tf
import numpy as np
tf.__version__


'2.5.0-dev20201101'

In [2]:
X = tf.random.normal(shape=(3, 1))
W_xh = tf.random.normal(shape=(1, 4))
H = tf.random.normal(shape=(3, 4))
W_hh = tf.random.normal(shape=(4, 4))

In [3]:
X_M = tf.matmul(X,W_xh)
X_M

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.23865157e-01, -4.51886654e-02, -1.29895344e-01,
         7.33046010e-02],
       [ 5.69931930e-04, -2.07923382e-04, -5.97678125e-04,
         3.37291218e-04],
       [-2.93629646e-01,  1.07122384e-01,  3.07924539e-01,
        -1.73772857e-01]], dtype=float32)>

In [4]:
H_M = tf.matmul(H, W_hh)
H_M


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.2654264 ,  1.208532  ,  2.4985871 , -1.8364582 ],
       [ 1.9883127 ,  2.7280428 ,  1.7890401 , -1.7207539 ],
       [-0.6031584 , -2.5213046 , -0.80639625, -0.9201181 ]],
      dtype=float32)>

In [5]:
X_M + H_M


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.3892915 ,  1.1633433 ,  2.3686917 , -1.7631536 ],
       [ 1.9888827 ,  2.727835  ,  1.7884424 , -1.7204167 ],
       [-0.89678806, -2.4141822 , -0.4984717 , -1.0938909 ]],
      dtype=float32)>

In [9]:
# RNN output
#tf.concat([W_xh,W_hh],axis=0)
tf.matmul(tf.concat([X,H],axis=1),tf.concat([W_xh,W_hh],axis=0))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.3892915 ,  1.1633433 ,  2.368692  , -1.7631537 ],
       [ 1.9888827 ,  2.727835  ,  1.7884424 , -1.7204167 ],
       [-0.89678806, -2.4141822 , -0.49847186, -1.0938909 ]],
      dtype=float32)>

In [10]:
'''
将矩阵X和H按列（维度1）连结，连结后的矩阵形状为(3, 5)。可见，
连结后矩阵在维度1的长度为矩阵X和H在维度1的长度之和（1+4）。然后，
将矩阵W_xh和W_hh按行（维度0）连结，连结后的矩阵形状为(5, 4)。
最后将两个连结后的矩阵相乘，得到与上面代码输出相同的形状为(3, 4)的矩阵。
'''

'\n'